url: https://hubx.work
baseurl: /

# Site settings
title: HUBX
email: contact@hubx.work
description: "Oferecemos soluções completas de projetos para empresas e empreendedores. Desde a concepção até a execução, nossa equipe especializada garante o sucesso do seu projeto com eficiência, inovação e personalização. Descubra como podemos ajudar a transformar suas ideias em realidade com expertise e dedicação."


# Team names, titles and social links
people:
- name: Francismar Araujo
  pic: 1
  position: Diretor Executivo
  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/francismararaujo/

- name: Vanessa Cristina
  pic: 2
  position: Diretora de Recursos Humanos
  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/vanessa-cristina-1%C2%B0-61b673136/

- name: Mateus Sá
  pic: 3
  position: Diretor de Design
  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/mateus-s%C3%A1-a96584157/


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: http://twitter.com/hubxwork
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/hubxwork
#  - title: bitbucket 
#    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/hubx-work

# Postal address (add as many lines as necessary)
address:
  - line: Av Marechal Castelo Branco 445
  - line: Contagem, MG

# Build settings
markdown: kramdown
permalink: pretty
