url: https://x-hub.co
baseurl: /

# Site settings
title: X-HUB
email: hello@x-hub.co
description: "We offer comprehensive project solutions for businesses and entrepreneurs. From conception to execution, our specialized team ensures the success of your project with efficiency, innovation, and customization. Discover how we can help turn your ideas into reality with expertise and dedication."


# Team names, titles and social links
people:
- name: Francismar Araujo
  pic: 1
  position: Engineering Studio
  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/francismararaujo/

- name: Vanessa Cristina
  pic: 2
  position: Central Studio
  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/vanessa-cristina-1%C2%B0-61b673136/

- name: Mateus Sá
  pic: 3
  position: Design Studio
  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/mateus-s%C3%A1-a96584157/


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: http://twitter.com/hubxwork
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/hubxwork
  - title: instagram
    url: https://www.instagram.com/xhubcollabs/
  - title: linkedin
    url: https://www.linkedin.com/company/xhubcollabs

# Postal address (add as many lines as necessary)
address:
  - line: Av Marechal Castelo Branco 445
  - line: Contagem, MG

# Build settings
markdown: kramdown
permalink: pretty
